### PR TITLE
Ensure filename is a string

### PR DESCRIPTION
**Pull request by radarhere**
https://github.com/python-pillow/Pillow/pull/5621 is failing at the moment.

This fixes it.

### CODE REVIEW

**Comment by radarhere** [comment]
@ntninja I've just rebased this.

I think this simplifies things, rather than every image plugin not knowing if `filename` is a string or not, and Jpeg2KImagePlugin having to use `os.fsdecode`. Let me know if you disagree.

**Comment by ntninja** [comment]
I kinda disagree in that I feel that not unnecessarily transforming the input parameters is a good thing, but that is really just my preference and not based on anything technical really.

In any case the `os.path.*` functions already call `os.fspath(…)` on their input parameter anyways, so you're not actually fixing doing what you think you're doing here. The call to `os.fsdecode(…)` is to ensure that the result of these functions is a `str` (not `bytes`!), as comparisons such as `b".jfif" == ".jfif"` will never be `True`.

**Comment by radarhere** [comment]
> you're not actually fixing doing what you think you're doing here.

...I'm not? ...I agree that this is about turning a potential byte variable to a string. My idea was to ensure that not just `ext`, but `filename` also is a string, so that Jpeg2KImagePlugin can rely on that. The code looks cleaner afterwards, still passes, and I can't see a neater way to do it.

**Comment by ntninja** [comment]
> > you're not actually fixing doing what you think you're doing here.
> 
> ...I'm not? ...I agree that this is about turning a potential byte variable to a string. My idea was to ensure that not just `ext`, but `filename` also is a string, so that Jpeg2KImagePlugin can rely on that. The code looks cleaner afterwards, still passes, and I can't see a neater way to do it.

Upps… Yes, you are fixing it correctly sorry. 😩

So it really just boils down to this:

> I kinda disagree in that I feel that not unnecessarily transforming the input parameters is a good thing, but that is really just my preference and not based on anything technical really.

But I think we have concluded at this point that that's not how you see things and you *are* in charge after all, so lets move on then… :slightly_smiling_face:

**Comment by radarhere** [comment]
Oh, I would be happy to let you continue to disagree with me. I just merged it because after 2 weeks with no reply I figured maybe you'd moved on to other things.

**Comment by ntninja** [comment]
> Oh, I would be happy for you to continue to disagree with me.

What do you mean? I told you why I prefer it differently and you told me you prefer it this way and you will have to deal with the fallout if it turns out to be the wrong decision (which from a maintenance PoV it probably isn't), what else is there to discuss here?

**Comment by radarhere** [comment]
Sorry, didn't mean to cause confusion. Nothing more needs to be done here.
I just meant that I didn't merge this because I thought I knew better - I merged it because I wasn't getting a response. It's your Pillow PR, you can ultimately do what you want.

**Pull request merged**
